-- Migration 003: Create the friendships table
--
-- Tracks the social connections between users. Each row represents one
-- friend request — who sent it, who received it, and the current status
-- (pending, accepted, or declined). Once accepted, each user can see
-- the other's friend-visible catches.
--
-- TODO: Add the actual CREATE TABLE statement here when implementing.
-- Note: Add foreign keys to the users table for both requester_id and recipient_id.
-- Note: Add a unique constraint on (requester_id, recipient_id) so you can't
--       accidentally create duplicate friend requests between the same two people.
